### ISSUE TITLE
'NoneType' object has no attribute 'ndim'

### ISSUE THREAD

**Issue by KiteA2022** [iboyles/makeittalknow#1]
340         image = image_or_path
    341 
--> 342     if image.ndim == 2:
    343         image = color.gray2rgb(image)
    344     elif image.ndim == 4:

AttributeError: 'NoneType' object has no attribute 'ndim'

**Comment by KiteA2022** [comment]
can you tell me

**Comment by iboyles** [comment]
you just need to change path of the image inside ' ' to 'image.jpg' image.jpg being one in the examples folder, your picture also needs to be 256x256 exactly if even 256 by 257 it won't work. I'm going to change notebook to have a default one instead of the one I added now.

code chunk where error is most likely needs to be fixed , change ian.jpg to one of the ones in examples
img =cv2.imread('examples/' + 'ian.jpg') ---> img =cv2.imread('examples/' + 'donald.jpg') 

import face_alignment
from skimage import io
img =cv2.imread('examples/' + 'ian.jpg') 
predictor = face_alignment.FaceAlignment(face_alignment.LandmarksType.THREE_D, device='cpu', flip_input=True)
shapes = predictor.get_landmarks(img)
if (not shapes or len(shapes) != 1):
    print('Cannot detect face landmarks. Exit.')
    exit(-1)
shape_3d = shapes[0]

if(opt_parser.close_input_face_mouth):
    util.close_input_face_mouth(shape_3d)

**Comment by KiteA2022** [comment]
> ok thanks

**Comment by iboyles** [comment]
alright I'm going to close the issue let me know if there are anymore problems
